#ifndef SERVERCC_SERVER_DEFAULTS_H
#define SERVERCC_SERVER_DEFAULTS_H

#ifndef SERVERCC_DEFAULT_PORT
#define SERVERCC_DEFAULT_PORT 8080
#endif

#ifndef SERVERCC_DEFAULT_MODE
#define SERVERCC_DEFAULT_MODE ServerMode::SYNC
#endif

#ifndef SERVERCC_BUFFER_SIZE
#define SERVERCC_BUFFER_SIZE 1024
#endif

#ifndef SERVERCC_DEFAULT_BACKLOG
#define SERVERCC_DEFAULT_BACKLOG 10
#endif

#endif
