#ifndef SERVERCC_DISTRIBUTED_PROTOCOLS_H
#define SERVERCC_DISTRIBUTED_PROTOCOLS_H

#ifndef SERVERCC_DISTRIBUTED_PROTOCOLS_CONNECT
#define SERVERCC_DISTRIBUTED_PROTOCOLS_CONNECT "connect"
#endif

#ifndef SERVERCC_DISTRIBUTED_PROTOCOLS_CONNECT_ACK
#define SERVERCC_DISTRIBUTED_PROTOCOLS_CONNECT_ACK "connect_ack"
#endif

#ifndef SERVERCC_DISTRIBUTED_PROTOCOLS_ANNOUNCE
#define SERVERCC_DISTRIBUTED_PROTOCOLS_ANNOUNCE "announce"
#endif

#endif
