#ifndef SERVERCC_DEFAULTS_H
#define SERVERCC_DEFAULTS_H

#ifndef SERVERCC_DEFAULT_PORT
#define SERVERCC_DEFAULT_PORT 8080
#endif

#ifndef SERVERCC_DEFAULT_MODE
#define SERVERCC_DEFAULT_MODE ServerMode::SINGLE_THREAD
#endif

#endif
